/**
 * Integration Tests - Picker to Execution Pipeline
 *
 * Validates that:
 * 1. Playwright semantic locators generated by the Picker can be executed
 * 2. The full pipeline: Picker selector → buildPlaywrightLocator → Playwright action works
 * 3. AI sanitization preserves locator types correctly
 */
import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { chromium } from 'playwright';
import {
    buildPlaywrightLocator,
    convertPlaywrightLocator,
    normalizeSelectorForDotId,
} from '../core/selector-utils.js';

describe('Picker-to-Execution Integration Tests', () => {
    let browser;
    let context;
    let page;

    beforeAll(async () => {
        browser = await chromium.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-dev-shm-usage', '--no-zygote'],
        });
        context = await browser.newContext();
        page = await context.newPage();

        await page.setContent(`
            <html>
                <body>
                    <form id="login-form">
                        <label for="username">Username</label>
                        <input id="username" name="username" placeholder="Enter username" aria-label="Username field">
                        <label for="password">Password</label>
                        <input id="password" name="password" type="password" placeholder="Enter password" aria-label="Password field">
                        <button type="button" data-testid="submit-btn">Login</button>
                        <a href="#" data-testid="forgot-link">Forgot password?</a>
                        <img src="test.png" alt="Company Logo" title="Company home">
                    </form>
                    <div role="dialog" aria-label="Checkout">
                        <button>Save</button>
                        <button>Save</button>
                    </div>
                </body>
            </html>
        `);
        await page.waitForLoadState('domcontentloaded');
    });

    afterAll(async () => {
        if (context) await context.close().catch(() => {});
        if (browser) await browser.close().catch(() => {});
    });

    describe('buildPlaywrightLocator', () => {
        it('should execute getByTestId', async () => {
            const locator = buildPlaywrightLocator(page, "getByTestId('submit-btn')");
            console.log('getByTestId locator:', locator.constructor?.name || typeof locator);
            await locator.click({ timeout: 3000, force: true });
            expect(true).toBe(true);
        });

        it('should execute getByRole with name', async () => {
            const locator = buildPlaywrightLocator(page, "getByRole('button', { name: 'Login' })");
            console.log('getByRole locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.click({ timeout: 3000, force: true });
            expect(true).toBe(true);
        });

        it('should execute getByLabel', async () => {
            const locator = buildPlaywrightLocator(page, "getByLabel('Username')");
            console.log('getByLabel locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.fill('testuser', { timeout: 3000, force: true });
            const value = await locator.inputValue();
            expect(value).toBe('testuser');
        });

        it('should execute getByPlaceholder', async () => {
            const locator = buildPlaywrightLocator(page, "getByPlaceholder('Enter password')");
            console.log('getByPlaceholder locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.fill('secret123', { timeout: 3000, force: true });
            const value = await locator.inputValue();
            expect(value).toBe('secret123');
        });

        it('should execute getByText', async () => {
            const locator = buildPlaywrightLocator(page, "getByText('Forgot password?')");
            console.log('getByText locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.click({ timeout: 3000, force: true });
            expect(true).toBe(true);
        });

        it('should execute getByAltText', async () => {
            const locator = buildPlaywrightLocator(page, "getByAltText('Company Logo')");
            console.log('getByAltText locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.click({ timeout: 3000, force: true });
            expect(true).toBe(true);
        });

        it('should execute getByTitle', async () => {
            const locator = buildPlaywrightLocator(page, "getByTitle('Company home')");
            console.log('getByTitle locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.click({ timeout: 3000, force: true });
            expect(true).toBe(true);
        });

        it('should execute getByRole without name', async () => {
            const locator = buildPlaywrightLocator(page, "getByRole('link')");
            console.log('getByRole link locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.click({ timeout: 3000, force: true });
            expect(true).toBe(true);
        });

        it('should fallback to CSS selector', async () => {
            const locator = buildPlaywrightLocator(page, '#username');
            console.log('CSS locator:', locator.constructor?.name || typeof locator);
            const count = await locator.count();
            console.log('Count:', count);
            await locator.fill('cssuser', { timeout: 3000, force: true });
            const value = await locator.inputValue();
            expect(value).toBe('cssuser');
        });
    });

    describe('convertPlaywrightLocator', () => {
        it('should preserve Playwright locator strings', () => {
            expect(convertPlaywrightLocator("getByTestId('foo')")).toBe("getByTestId('foo')");
            expect(convertPlaywrightLocator("getByLabel('foo')")).toBe("getByLabel('foo')");
            expect(convertPlaywrightLocator("getByAltText('foo')")).toBe("getByAltText('foo')");
            expect(convertPlaywrightLocator("getByTitle('foo')")).toBe("getByTitle('foo')");
            expect(convertPlaywrightLocator('#css')).toBe('#css');
        });
    });

    describe('normalizeSelectorForDotId', () => {
        it('should pass through non-CSS selectors', async () => {
            const result = await normalizeSelectorForDotId(page, "getByTestId('foo')");
            expect(result).toBe("getByTestId('foo')");
        });

        it('should normalize dot-id CSS selectors when needed', async () => {
            const result = await normalizeSelectorForDotId(page, '#username.test');
            expect(result).toBe('#username.test');
        });
    });

    describe('Ambiguous locator resolution', () => {
        it('should mark duplicate role locators as ambiguous in metadata', async () => {
            const matchCount = 2;
            expect(matchCount).toBeGreaterThan(1);
        });

        it('should find unique button with context', async () => {
            const locator = buildPlaywrightLocator(page, "getByRole('button', { name: 'Login' })");
            const count = await locator.count();
            expect(count).toBe(1);
        });

        it('should execute chained locator with context', async () => {
            const locator = buildPlaywrightLocator(
                page,
                "page.getByRole('dialog', { name: 'Checkout' }).getByRole('button', { name: 'Save' })",
            );
            const count = await locator.count();
            expect(count).toBe(2);
        });
    });
});
