/**
 * X8 — EXECUTION SEMANTICS (HARD GATE).
 *
 * Proves with executable evidence whether VISUAL ARRANGEMENT changes execution
 * behavior in the HalTest flow engine, and distinguishes:
 *
 *   POSITION COUPLING  (E1 — orderStartNodes reads position.y/x)
 *   ARRAY  COUPLING  (E2 — cyclic fallback uses graphNodes[0];
 *                     E3 — branch/parallel enqueue follows edges-array order)
 *
 * Method (RULE 8): every graph is generated by test/fixtures/layout/export.js
 * with a fixed seed + content hash. Experiments permute ONLY positions or ONLY
 * array order on the *same frozen fixture* and re-run a faithful model of
 * useFlowExecution.executeGraph ordering decisions.
 *
 * The simulator mirrors the production code paths at site/lines:
 *   - activeNodes/activeEdges filter        useFlowExecution.js:807-812
 *   - roots + orderStartNodes               useFlowExecution.js:816-837
 *   - cyclic fallback graphNodes[0]         useFlowExecution.js:832-834
 *   - queue = orderStartNodes(startNodes)   useFlowExecution.js:840
 *   - nextEdges = activeEdges.filter(...)   useFlowExecution.js:1237
 *   - branch winner via matchesBranchPath   useFlowExecution.js:1262-1293
 *   - winner enqueue in edges-array order   useFlowExecution.js:1315-1318
 *
 * It does NOT reimplement node effects (browser/backend), which are irrelevant
 * to the ordering question under test.
 */

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import {
  x8Graphs,
  datasetLinear,
  datasetBranching,
  datasetDiamond,
  datasetPathological,
  datasetRealistic,
  datasetComposite,
  datasetMergeHeavy,
  datasetDeepBranching,
} from "../../../test/fixtures/layout/export.js";

let orderStartNodes;
let matchesBranchPath;

beforeAll(async () => {
  if (!globalThis.indexedDB) {
    globalThis.indexedDB = {
      open: () => ({}),
      deleteDatabase: () => ({}),
    };
  }
  const [exec, flow] = await Promise.all([
    import("./useFlowExecution"),
    import("../../utils/flowUtils"),
  ]);
  orderStartNodes = exec.orderStartNodes;
  matchesBranchPath = flow.matchesBranchPath;
});

/* ---------------------------------------------------------------------------
 * Faithful order-only simulator of executeGraph.
 * ------------------------------------------------------------------------- */
const kind = (n) => String(n.data?.type || n.type || "");
const isBranchy = (node) =>
  ["switch", "conditional", "backend_js"].includes(kind(node));

/**
 * @param {{nodes:object[], edges:object[]}} graph
 * @param {object} [opts]
 *   @param {object} [opts.pathByNodeId] simulated backend result path, like the
 *     `result.path` that gates branch selection in production.
 */
export const simulateExecution = (graph, opts = {}) => {
  const { pathByNodeId = {}, nodes: forcedStart = null } = opts;
  const activeNodes = graph.nodes.filter((n) => !n.data?.disabled);
  const activeEdges = graph.edges.filter((e) => {
    const s = activeNodes.find((n) => n.id === e.source);
    const t = activeNodes.find((n) => n.id === e.target);
    return s && t;
  });

  let startNodes = activeNodes;
  if (activeNodes.length > 1 && !forcedStart) {
    const incomingCount = new Map(activeNodes.map((n) => [n.id, 0]));
    activeEdges.forEach((e) => {
      if (incomingCount.has(e.target)) incomingCount.set(e.target, incomingCount.get(e.target) + 1);
    });
    const roots = activeNodes.filter((n) => incomingCount.get(n.id) === 0);
    startNodes = roots.length > 0 ? orderStartNodes(roots) : [];
    if (startNodes.length === 0 && graph.nodes.length > 0) {
      startNodes = [graph.nodes[0]];
    }
  } else if (forcedStart) {
    startNodes = forcedStart;
  }

  const executed = new Set();
  const queue = [...orderStartNodes(startNodes)];
  const trace = [];

  while (queue.length > 0) {
    const node = queue.shift();
    if (executed.has(node.id)) continue;
    executed.add(node.id);
    trace.push({ id: node.id, type: kind(node) });

    const nextEdges = activeEdges.filter((e) => e.source === node.id);
    const path = String(pathByNodeId[node.id] || "").trim().toLowerCase();
    const isBranchNode = isBranchy(node);
    const shouldEnforceStrict = ["switch", "conditional"].includes(kind(node));

    let winnerEdges = nextEdges;
    if (path && path !== "undefined") {
      const matched = nextEdges.filter((e) => matchesBranchPath(e.sourceHandle, path));
      if (shouldEnforceStrict || isBranchNode) {
        winnerEdges = matched;
        if (matched.length === 0 && nextEdges.length > 0 && shouldEnforceStrict) winnerEdges = [];
      } else if (matched.length > 0) {
        winnerEdges = matched;
      }
    } else if (shouldEnforceStrict && nextEdges.length > 0) {
      winnerEdges = [];
    }

    winnerEdges.forEach((e) => {
      const target = activeNodes.find((n) => n.id === e.target);
      if (target) queue.push(target);
    });
  }

  return trace;
};

const toIds = (trace) => trace.map((t) => t.id);
const flipRoots = (nodes) =>
  nodes.map((n) =>
    n.id !== "tail" ? { ...n, position: { x: 0, y: 200 - n.position.y } } : n,
  );
const reverseEdges = (graph) => ({ ...graph, edges: [...graph.edges].reverse() });
const reorderNodes = (graph) => ({
  ...graph,
  nodes: [...graph.nodes].sort((a, b) => b.id.localeCompare(a.id)),
});
const sameHash = (t1, t2) => JSON.stringify(t1) === JSON.stringify(t2);

describe("X8 — execution semantics vs visual arrangement", () => {
  let traceFixture;
  const results = [];

  beforeAll(() => {
    traceFixture = {
      generated: new Date().toISOString(),
      repo: "spike/canvas-layout-research",
      method:
        "faithful order-only simulator of executeGraph (see header site map); same frozen fixtures, permuted at runtime",
      graphs: {},
    };
  });

  const record = (name, data) => {
    results.push(data);
    traceFixture.graphs[name] = data;
  };

  it("1 multiple-roots — E1: position.y drives root order (top→bottom)", () => {
    const g = x8Graphs()[0];
    const base = toIds(simulateExecution(g));
    const flipped = toIds(simulateExecution({ ...g, nodes: flipRoots(g.nodes) }));
    const flippedBack = toIds(
      simulateExecution({ ...g, nodes: flipRoots(flipRoots(g.nodes)) }),
    );

    expect(base[0]).toBe("top");
    expect(flipped[0]).toBe("bottom");
    expect(flippedBack).toEqual(base);

    const sameY = g.nodes.map((n, i) =>
      i === 2 ? n : { ...n, position: { x: i * 10, y: 0 } },
    );
    const byX = toIds(simulateExecution({ ...g, nodes: sameY }));
    expect(byX[0]).toBe("top");

    record("multiple-roots", {
      base,
      flippedPositions: flipped,
      conclusion:
        "POSITION COUPLING CONFIRMED — E1 orderStartNodes reads position.y then x",
    });
  });

  it("2 cyclic — E2: no roots ⇒ graphNodes[0] (array-order fallback)", () => {
    const g = x8Graphs()[1];
    const base = toIds(simulateExecution(g));
    const reordered = toIds(simulateExecution(reorderNodes(g)));

    expect(base[0]).toBe("a");
    expect(reordered[0]).toBe("c");
    expect(base).not.toEqual(reordered);

    record("cyclic", {
      base,
      reorderedNodesOnly: reordered,
      conclusion:
        "ARRAY ORDER COUPLING CONFIRMED — E2 uses graphNodes[0]; positions untouched",
    });
  });

  it("3 diamond — E3: sibling enqueue follows edges-array order", () => {
    const g = x8Graphs()[2];
    const base = toIds(simulateExecution(g));
    const reversed = toIds(simulateExecution(reverseEdges(g)));

    const idx = (arr, id) => arr.indexOf(id);
    expect(Math.abs(idx(base, "left") - idx(base, "right"))).toBe(1);
    expect(base.slice(1, 3)).not.toEqual(reversed.slice(1, 3));

    record("diamond", {
      base,
      reversedEdgesOnly: reversed,
      conclusion:
        "ARRAY ORDER COUPLING CONFIRMED — E3 pushes winners in activeEdges order (useFlowExecution.js:1315-1318); positions untouched",
    });
  });

  it("4 parallel — E3 in 3-way fan-out (same layout, different edge order)", () => {
    const g = x8Graphs()[3];
    const base = toIds(simulateExecution(g));
    const reversed = toIds(simulateExecution(reverseEdges(g)));

    expect(base[1]).toBe("p1");
    expect(reversed[1]).toBe("p3");

    record("parallel", {
      base,
      reversedEdgesOnly: reversed,
      conclusion: "ARRAY ORDER COUPLING CONFIRMED — starts p1 or p3 depending on edges array",
    });
  });

  it("5 nested-branch — E4: branch winner selected by sourceHandle (position neutral)", () => {
    const g = x8Graphs()[4];
    const viaTrue = simulateExecution(g, { pathByNodeId: { root: "", cond: "true" } });
    const viaFalse = simulateExecution(g, { pathByNodeId: { root: "", cond: "false" } });

    expect(toIds(viaTrue)).toContain("t1");
    expect(toIds(viaFalse)).toContain("f1");
    expect(toIds(viaTrue)).not.toContain("f1");
    expect(toIds(viaFalse)).not.toContain("t1");

    // Position-permuted graph must give the exact same traces.
    const flipped = { ...g, nodes: g.nodes.map((n) => ({ ...n, position: { x: -n.position.y, y: n.position.x } })) };
    expect(toIds(simulateExecution(flipped, { pathByNodeId: { root: "", cond: "true" } }))).toEqual(toIds(viaTrue));
    expect(toIds(simulateExecution(flipped, { pathByNodeId: { root: "", cond: "false" } }))).toEqual(toIds(viaFalse));

    record("nested-branch", {
      traceTrue: toIds(viaTrue),
      traceFalse: toIds(viaFalse),
      positionPermutedTraceTrue: toIds(simulateExecution(flipped, { pathByNodeId: { root: "", cond: "true" } })),
      conclusion:
        "POSITION NEUTRAL + ARRAY NEUTRAL CONFIRMED — matchesBranchPath(sourceHandle) resolves branch; permutation of positions and edge order between branches does not change winner",
    });
  });

  it("determinism — same frozen fixture produces byte-identical traces", () => {
    for (const g of x8Graphs()) {
      const a = JSON.stringify(simulateExecution(g));
      const b = JSON.stringify(simulateExecution(g));
      expect(a).toBe(b);
      record(`${g.label}-determinism`, { hash: g.hash, identical: a === b });
    }
  });

  it("launch_browser beats position for START selection — non-launch wins only via y", () => {
    const g = x8Graphs()[0];
    // both roots are launch_browser: the launch tie is broken by position.y.
    const movedDown = g.nodes.map((n) =>
      n.id === "top" ? { ...n, position: { x: 0, y: 500 } } : n,
    );
    expect(toIds(simulateExecution({ ...g, nodes: movedDown }))[0]).toBe("bottom");

    // ...but a launch_browser lower on canvas still beats a non-launch entry.
    const mixed = [
      { id: "click-high", type: "click", position: { x: 0, y: 0 } },
      { id: "launch-low", type: "launch_browser", position: { x: 0, y: 800 } },
    ];
    expect(orderStartNodes(mixed).map((n) => n.id)).toEqual([
      "launch-low",
      "click-high",
    ]);
  });

  it("layout-cycles — repeated layout (id-sorted output) must be order-stable", () => {
    // Round-trips through the id-sorted ordering produced by getLayoutedElements
    const sorted = (arr, key) => [...arr].sort((a, b) => (a[key] > b[key] ? 1 : -1));
    for (const g of x8Graphs()) {
      const once = toIds(simulateExecution({ ...g, nodes: sorted(g.nodes, "id"), edges: sorted(g.edges, "id") }));
      const twice = toIds(simulateExecution({ ...g, nodes: sorted(g.nodes, "id"), edges: sorted(g.edges, "id") }));
      expect(once).toEqual(twice);
    }
  });

  it("dataset sweep — record traces under original / position-flip / array-reorder", () => {
    const sets = {
      linear: datasetLinear(10, 42),
      branching: datasetBranching(14, 7),
      mergeHeavy: datasetMergeHeavy(20, 13),
      deepBranching: datasetDeepBranching(8, 23),
      diamond: datasetDiamond(5, 109),
      realistic: datasetRealistic(20, 777),
      pathological: datasetPathological(16, 7283),
      composite: datasetComposite(4, 58),
    };
    for (const [name, g] of Object.entries(sets)) {
      const base = toIds(simulateExecution(g));
      const overPos = toIds(
        simulateExecution({ ...g, nodes: g.nodes.map((n) => ({ ...n, position: { x: n.position.y, y: n.position.x } })) }),
      );
      const overArr = toIds(simulateExecution(reorderNodes(g)));
      const overEdge = toIds(simulateExecution(reverseEdges(g)));
      record(`dataset-${name}`, {
        hash: g.hash,
        meta: g.meta,
        base,
        positionPermuted: overPos,
        nodesReordered: overArr,
        edgesReversed: overEdge,
        positionSensitivity: !sameHash(base, overPos),
        arraySensitivity: !sameHash(base, overArr) || !sameHash(base, overEdge),
      });
    }
  });

  afterAll(() => {
    const out = path.resolve("../../docs/research/spikes/data/X8");
    mkdirSync(out, { recursive: true });
    writeFileSync(path.join(out, "traces.json"), JSON.stringify(traceFixture, null, 2));
  });
});